#!/usr/bin/env python3
"""
Register Bot in DB
------------------
Utility script to quickly register a new JSON configuration into the PostgreSQL database.
This is necessary for the enhanced live_trading_bot architecture, which reads configs
from the DB rather than the file system.

Usage:
    python scripts/register_bot_in_db.py configs/bots/sentiment_bot.json
"""

import argparse
import json
import sys
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from src.data.db.services.trading_service import trading_service
from src.notification.logger import setup_logger
from src.trading.services.bot_config_validator import validate_bot_config_json

_logger = setup_logger("register_bot")


def register_bot(config_path: str, user_id: int):
    """Read a bot config JSON and upsert it to the database."""
    config_file = Path(config_path)
    if not config_file.exists():
        _logger.error(f"Configuration file not found: {config_path}")
        return False

    with open(config_file) as f:
        config_text = f.read()

    # 1. Validate the JSON content first natively
    is_valid, errors, warnings = validate_bot_config_json(config_text)
    if not is_valid:
        _logger.error(f"Configuration is invalid. Errors: {errors}")
        return False

    if warnings:
        _logger.warning(f"Configuration warnings: {warnings}")

    config_dict = json.loads(config_text)

    bot_data = {
        "id": None,  # Will be auto-generated by the database OR can pass a string ID if using string IDs
        "user_id": user_id,
        "status": "stopped",  # Default to stopped
        "description": config_dict.get("description", ""),
        "config": config_dict,
    }

    # Let's ensure 'name' is in the config, the DB uses it.
    if "name" not in config_dict:
        _logger.error("The JSON config must contain a 'name' field.")
        return False

    try:
        # Upsert returns the created bot details
        result = trading_service.upsert_bot(bot_data)
        _logger.info(f"✅ Successfully registered bot '{config_dict['name']}' in the database!")
        _logger.info(f"Bot DB ID: {result.get('id')}")
        return True
    except Exception as e:
        _logger.exception(f"Failed to upsert bot to database: {e}")
        return False


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Register a JSON bot configuration to the PostgreSQL database.")
    parser.add_argument("config_file", type=str, help="Path to the bot configuration JSON file")
    parser.add_argument("--user-id", type=int, default=1, help="The User ID to associate this bot with (default: 1)")

    args = parser.parse_args()
    success = register_bot(args.config_file, args.user_id)
    sys.exit(0 if success else 1)
