"""Stage 4 — Output generation: CSV/MD/JSON writers + Telegram/email formatters."""

import json
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
import sys

PROJECT_ROOT = Path(__file__).resolve().parents[5]
sys.path.insert(0, str(PROJECT_ROOT))

import pandas as pd

from src.ml.pipeline.p05_ai_selector.config import RESULTS_BASE
from src.notification.logger import setup_logger

_logger = setup_logger(__name__)

_TELEGRAM_MAX_CHARS = 3800
_DISCLAIMER = (
    "Disclaimer: This report is generated by an automated AI system for informational "
    "purposes only. It is not financial advice. Past signal performance does not guarantee "
    "future results. Always conduct your own research before making investment decisions."
)


class Stage4Output:
    """Writes all output artefacts and formats notification messages."""

    def __init__(self, results_base: Optional[Path] = None):
        self._results_base = results_base or RESULTS_BASE

    def write_results(
        self,
        picks: List[Dict[str, Any]],
        stage2_df: pd.DataFrame,
        metadata: Dict[str, Any],
        run_date: date,
    ) -> Path:
        """
        Write all output files for the given run.

        Args:
            picks: List of 5 pick dicts from Stage 3.
            stage2_df: Full Stage 2 ranking (top-25 rows).
            metadata: Run metadata dict.
            run_date: Date of the run.

        Returns:
            Path to the run results directory.
        """
        run_dir = self._results_base / str(run_date)
        run_dir.mkdir(parents=True, exist_ok=True)

        self._write_top_picks_csv(picks, run_dir)
        self._write_full_ranking_csv(picks, stage2_df, run_dir)
        self._write_report_md(picks, metadata.get("market_context", ""), metadata, run_date, run_dir)
        self._write_metadata_json(metadata, run_dir)

        _logger.info("Stage4: results written to %s", run_dir)
        return run_dir

    def format_telegram(
        self,
        picks: List[Dict[str, Any]],
        trigger_reason: str,
        run_date: date,
    ) -> str:
        """
        Format the Telegram notification message (top 3 picks, condensed).

        Args:
            picks: Full list of picks (top 3 used).
            trigger_reason: Human-readable reason for notification.
            run_date: Run date.

        Returns:
            Telegram-safe message string (≤ 3800 chars).
        """
        lines = [
            f"P05 AI Selector — {run_date}",
            f"Trigger: {trigger_reason}",
            "",
        ]
        for pick in picks[:3]:
            exit_strat = pick.get("exit_strategy", {})
            breakers = exit_strat.get("thesis_breakers", [])
            targets = exit_strat.get("profit_targets", [])
            first_breaker = breakers[0] if breakers else "n/a"
            second_breaker = breakers[1] if len(breakers) > 1 else ""
            first_target = targets[0] if targets else {}
            target_str = (
                f"${first_target.get('price_level', '?')} → {first_target.get('action', '')}"
                if first_target else "n/a"
            )

            lines += [
                f"{pick['rank']}. ${pick['ticker']} [{pick['bias']}] "
                f"conf {pick['confidence']}/10 | {pick.get('time_horizon', '?')}",
                f'   "{pick["thesis"]}"',
                f"   Exit if: {first_breaker}" + (f"; {second_breaker}" if second_breaker else ""),
                f"   First target: {target_str}",
                "",
            ]

        lines.append(f"Full report: {self._results_base}/{run_date}/report.md")
        msg = "\n".join(lines)

        if len(msg) > _TELEGRAM_MAX_CHARS:
            msg = msg[: _TELEGRAM_MAX_CHARS - 3] + "..."
            _logger.warning("Stage4: Telegram message truncated to %d chars", _TELEGRAM_MAX_CHARS)

        return msg

    def format_email_html(
        self,
        picks: List[Dict[str, Any]],
        market_context: str,
        trigger_reason: str,
        run_date: date,
    ) -> str:
        """
        Format the full HTML email report (top 5 with complete exit strategies).

        Args:
            picks: All 5 picks.
            market_context: LLM market context paragraph.
            trigger_reason: Notification trigger string.
            run_date: Run date.

        Returns:
            HTML string ready for email delivery.
        """
        pick_rows = "".join(
            f"<tr><td>{p['rank']}</td><td><b>{p['ticker']}</b></td>"
            f"<td>{p['bias']}</td><td>{p['confidence']}/10</td>"
            f"<td>{p.get('time_horizon','?')}</td>"
            f"<td>{'⚠ Earnings' if p.get('earnings_flag') else ''}</td>"
            f"<td>{p['thesis'][:120]}…</td></tr>"
            for p in picks
        )

        pick_sections = ""
        for p in picks:
            ex = p.get("exit_strategy", {})
            add_cond = "".join(f"<li>{c}</li>" for c in ex.get("add_conditions", []))
            hold_cond = "".join(f"<li>{c}</li>" for c in ex.get("hold_conditions", []))
            breakers = "".join(f"<li>{c}</li>" for c in ex.get("thesis_breakers", []))
            targets_html = "".join(
                f"<li><b>${t.get('price_level','?')}</b> — {t.get('action','')} "
                f"<i>{t.get('note','')}</i></li>"
                for t in ex.get("profit_targets", [])
            )
            risk_html = "".join(f"<li>{r}</li>" for r in p.get("risk_factors", []))

            pick_sections += f"""
<h3>#{p['rank']} {p['ticker']} [{p['bias']}] — confidence {p['confidence']}/10</h3>
<p><b>Thesis:</b> {p['thesis']}</p>
<p><b>Time Horizon:</b> {p.get('time_horizon','?')}</p>
<h4>Risk Factors</h4><ul>{risk_html}</ul>
<h4>Position Management</h4>
<p><i>Entry conditions (when/where to add):</i></p><ul>{add_cond}</ul>
<p><i>Hold conditions (what must remain true):</i></p><ul>{hold_cond}</ul>
<p><i>Thesis-breakers (exit immediately if any):</i></p><ul>{breakers}</ul>
<p><i>Profit targets:</i></p><ul>{targets_html}</ul>
<p><i>Time horizon note:</i> {ex.get('time_horizon_note','')}</p>
<hr/>"""

        html = f"""<!DOCTYPE html><html><body style="font-family:Arial,sans-serif;max-width:800px;margin:auto">
<h1>P05 AI Selector — {run_date}</h1>
<p><b>Trigger:</b> {trigger_reason}</p>
<h2>Market Context</h2><p>{market_context}</p>
<h2>Summary</h2>
<table border="1" cellpadding="4" cellspacing="0" style="border-collapse:collapse;width:100%">
<tr style="background:#f0f0f0">
  <th>#</th><th>Ticker</th><th>Bias</th><th>Confidence</th>
  <th>Horizon</th><th>Earnings</th><th>Thesis</th>
</tr>{pick_rows}
</table>
<h2>Picks Detail</h2>
{pick_sections}
<p style="color:#888;font-size:0.8em">{_DISCLAIMER}</p>
</body></html>"""
        return html

    def should_notify(
        self,
        p18_signals_count: int,
        notification_override: bool,
    ) -> Tuple[bool, str]:
        """
        Apply dual OR-trigger logic per spec §4.

        Returns:
            (should_notify: bool, trigger_reason: str)
        """
        if p18_signals_count >= 1:
            return (True, f"P18 flagged {p18_signals_count} high-score ticker(s)")
        if notification_override:
            return (True, "LLM assigned confidence ≥ 9 for at least one pick")
        return (False, "no trigger conditions met")

    # ------------------------------------------------------------------
    # Private writers
    # ------------------------------------------------------------------

    def _write_top_picks_csv(self, picks: List[Dict[str, Any]], run_dir: Path) -> None:
        rows = []
        for p in picks:
            targets = p.get("exit_strategy", {}).get("profit_targets", [])
            first_target = targets[0] if targets else {}
            rows.append({
                "rank": p["rank"],
                "ticker": p["ticker"],
                "confidence": p["confidence"],
                "bias": p["bias"],
                "thesis": p["thesis"],
                "time_horizon": p.get("time_horizon", ""),
                "first_profit_target_price": first_target.get("price_level", ""),
                "first_profit_target_action": first_target.get("action", ""),
            })
        pd.DataFrame(rows).to_csv(run_dir / "top_picks.csv", index=False)

    def _write_full_ranking_csv(
        self, picks: List[Dict[str, Any]], stage2_df: pd.DataFrame, run_dir: Path
    ) -> None:
        pick_map = {p["ticker"]: p for p in picks}
        df = stage2_df.copy()
        df["llm_rank"] = df["ticker"].map(lambda t: pick_map.get(t, {}).get("rank", ""))
        df["llm_confidence"] = df["ticker"].map(lambda t: pick_map.get(t, {}).get("confidence", ""))
        df.to_csv(run_dir / "full_ranking.csv", index=False)

    def _write_report_md(
        self,
        picks: List[Dict[str, Any]],
        market_context: str,
        metadata: Dict[str, Any],
        run_date: date,
        run_dir: Path,
    ) -> None:
        trigger = metadata.get("trigger_reason", "")
        lines = [
            f"# P05 AI Selector — {run_date}",
            f"**Trigger:** {trigger}",
            "",
            "## Market Context",
            market_context,
            "",
            "## Top Picks",
            "",
        ]
        for p in picks:
            ex = p.get("exit_strategy", {})
            lines += [
                f"### #{p['rank']} {p['ticker']} [{p['bias']}] — Confidence {p['confidence']}/10",
                f"**Thesis:** {p['thesis']}",
                f"**Time Horizon:** {p.get('time_horizon', '?')}",
                "",
                "**Risk Factors:**",
                *[f"- {r}" for r in p.get("risk_factors", [])],
                "",
                "**Entry Conditions:**",
                *[f"- {c}" for c in ex.get("add_conditions", [])],
                "",
                "**Hold Conditions:**",
                *[f"- {c}" for c in ex.get("hold_conditions", [])],
                "",
                "**Thesis-Breakers (exit immediately):**",
                *[f"- {b}" for b in ex.get("thesis_breakers", [])],
                "",
                "**Profit Targets:**",
                *[f"- ${t.get('price_level','?')} — {t.get('action','')} _{t.get('note','')}_"
                  for t in ex.get("profit_targets", [])],
                "",
                f"*{ex.get('time_horizon_note', '')}*",
                "",
                "---",
                "",
            ]
        lines.append(f"*{_DISCLAIMER}*")
        (run_dir / "report.md").write_text("\n".join(lines), encoding="utf-8")

    def _write_metadata_json(self, metadata: Dict[str, Any], run_dir: Path) -> None:
        (run_dir / "metadata.json").write_text(
            json.dumps(metadata, indent=2, default=str), encoding="utf-8"
        )
