"""initial_schema

Revision ID: 7248560962fe
Revises: 
Create Date: 2025-11-02 21:47:31.575013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7248560962fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentiment_payloads')
    op.alter_column('job_schedule_runs', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('job_schedule_runs', 'job_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('job_schedule_runs', 'enqueued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('ux_runs_job_scheduled_for'), table_name='job_schedule_runs')
    op.create_unique_constraint('ux_runs_job_scheduled_for', 'job_schedule_runs', ['job_type', 'job_id', 'scheduled_for'])
    op.create_index(op.f('ix_job_schedule_runs_id'), 'job_schedule_runs', ['id'], unique=False)
    op.drop_constraint(op.f('job_schedule_runs_job_id_fkey'), 'job_schedule_runs', type_='foreignkey')
    op.alter_column('job_schedules', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('job_schedules', 'task_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('job_schedules', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('job_schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('job_schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.create_index('idx_schedules_enabled', 'job_schedules', ['enabled'], unique=False)
    op.create_index('idx_schedules_next_run_at', 'job_schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_job_schedules_enabled'), 'job_schedules', ['enabled'], unique=False)
    op.create_index(op.f('ix_job_schedules_id'), 'job_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_job_schedules_next_run_at'), 'job_schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_job_schedules_user_id'), 'job_schedules', ['user_id'], unique=False)
    op.create_unique_constraint('unique_user_schedule_name', 'job_schedules', ['user_id', 'name'])
    op.alter_column('msg_channel_configs', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('msg_channel_configs', 'rate_limit_per_minute',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('msg_channel_configs', 'max_retries',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('msg_channel_configs', 'timeout_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('msg_channel_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('msg_channel_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_channel_configs_enabled'), table_name='msg_channel_configs')
    op.drop_index(op.f('idx_channel_configs_updated'), table_name='msg_channel_configs')
    op.drop_constraint(op.f('msg_channel_configs_channel_key'), 'msg_channel_configs', type_='unique')
    op.create_index(op.f('ix_msg_channel_configs_enabled'), 'msg_channel_configs', ['enabled'], unique=False)
    op.create_index(op.f('ix_msg_channel_configs_id'), 'msg_channel_configs', ['id'], unique=False)
    op.create_index(op.f('ix_msg_channel_configs_updated_at'), 'msg_channel_configs', ['updated_at'], unique=False)
    op.create_unique_constraint(op.f('uq_msg_channel_configs_channel'), 'msg_channel_configs', ['channel'])
    op.drop_table_comment(
        'msg_channel_configs',
        existing_comment='Channel plugin configuration and settings',
        schema=None
    )
    op.alter_column('msg_delivery_status', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_delivery_status_channel'), table_name='msg_delivery_status')
    op.drop_index(op.f('idx_delivery_status_composite'), table_name='msg_delivery_status')
    op.drop_index(op.f('idx_delivery_status_delivered'), table_name='msg_delivery_status')
    op.drop_index(op.f('idx_delivery_status_message'), table_name='msg_delivery_status')
    op.drop_index(op.f('idx_delivery_status_status'), table_name='msg_delivery_status')
    op.create_index(op.f('ix_msg_delivery_status_channel'), 'msg_delivery_status', ['channel'], unique=False)
    op.create_index(op.f('ix_msg_delivery_status_delivered_at'), 'msg_delivery_status', ['delivered_at'], unique=False)
    op.create_index(op.f('ix_msg_delivery_status_id'), 'msg_delivery_status', ['id'], unique=False)
    op.create_index(op.f('ix_msg_delivery_status_message_id'), 'msg_delivery_status', ['message_id'], unique=False)
    op.create_index(op.f('ix_msg_delivery_status_status'), 'msg_delivery_status', ['status'], unique=False)
    op.drop_table_comment(
        'msg_delivery_status',
        existing_comment='Per-channel delivery status tracking for each message',
        schema=None
    )
    op.alter_column('msg_messages', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('msg_messages', 'channels',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=False)
    op.alter_column('msg_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('msg_messages', 'scheduled_for',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('msg_messages', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('msg_messages', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('msg_messages', 'max_retries',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_msg_messages_created'), table_name='msg_messages')
    op.drop_index(op.f('idx_msg_messages_locked_at'), table_name='msg_messages')
    op.drop_index(op.f('idx_msg_messages_locked_by'), table_name='msg_messages')
    op.drop_index(op.f('idx_msg_messages_pending_poll'), table_name='msg_messages', postgresql_where="((status)::text = 'PENDING'::text)")
    op.drop_index(op.f('idx_msg_messages_pending_priority'), table_name='msg_messages', postgresql_where="((status)::text = 'PENDING'::text)")
    op.drop_index(op.f('idx_msg_messages_priority'), table_name='msg_messages')
    op.drop_index(op.f('idx_msg_messages_recipient'), table_name='msg_messages')
    op.drop_index(op.f('idx_msg_messages_retry_eligible'), table_name='msg_messages', postgresql_where="((status)::text = 'FAILED'::text)")
    op.drop_index(op.f('idx_msg_messages_scheduled'), table_name='msg_messages')
    op.drop_index(op.f('idx_msg_messages_status'), table_name='msg_messages')
    op.drop_index(op.f('idx_msg_messages_type'), table_name='msg_messages')
    op.create_index(op.f('ix_msg_messages_created_at'), 'msg_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_messages_id'), 'msg_messages', ['id'], unique=False)
    op.create_index(op.f('ix_msg_messages_locked_at'), 'msg_messages', ['locked_at'], unique=False)
    op.create_index(op.f('ix_msg_messages_locked_by'), 'msg_messages', ['locked_by'], unique=False)
    op.create_index(op.f('ix_msg_messages_message_type'), 'msg_messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_msg_messages_recipient_id'), 'msg_messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_msg_messages_scheduled_for'), 'msg_messages', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_msg_messages_status'), 'msg_messages', ['status'], unique=False)
    op.drop_table_comment(
        'msg_messages',
        existing_comment='Notification messages queue with priority and retry support',
        schema=None
    )
    op.alter_column('msg_rate_limits', 'last_refill',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('msg_rate_limits', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_rate_limits_channel'), table_name='msg_rate_limits')
    op.drop_index(op.f('idx_rate_limits_last_refill'), table_name='msg_rate_limits')
    op.drop_index(op.f('idx_rate_limits_user'), table_name='msg_rate_limits')
    op.create_index(op.f('ix_msg_rate_limits_channel'), 'msg_rate_limits', ['channel'], unique=False)
    op.create_index(op.f('ix_msg_rate_limits_id'), 'msg_rate_limits', ['id'], unique=False)
    op.create_index(op.f('ix_msg_rate_limits_last_refill'), 'msg_rate_limits', ['last_refill'], unique=False)
    op.create_index(op.f('ix_msg_rate_limits_user_id'), 'msg_rate_limits', ['user_id'], unique=False)
    op.drop_table_comment(
        'msg_rate_limits',
        existing_comment='Per-user rate limiting configuration and state',
        schema=None
    )
    op.alter_column('msg_system_health', 'component',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('msg_system_health', 'failure_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('msg_system_health', 'checked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_channel_health_checked'), table_name='msg_system_health')
    op.drop_index(op.f('idx_channel_health_status'), table_name='msg_system_health')
    op.drop_index(op.f('idx_system_health_system'), table_name='msg_system_health')
    op.drop_index(op.f('idx_system_health_unique'), table_name='msg_system_health')
    op.drop_constraint(op.f('msg_channel_health_channel_key'), 'msg_system_health', type_='unique')
    op.create_index(op.f('ix_msg_system_health_checked_at'), 'msg_system_health', ['checked_at'], unique=False)
    op.create_index(op.f('ix_msg_system_health_id'), 'msg_system_health', ['id'], unique=False)
    op.create_index(op.f('ix_msg_system_health_status'), 'msg_system_health', ['status'], unique=False)
    op.create_index(op.f('ix_msg_system_health_system'), 'msg_system_health', ['system'], unique=False)
    op.drop_table_comment(
        'msg_system_health',
        existing_comment='Health monitoring for notification channels',
        schema=None
    )
    op.alter_column('ss_ad_hoc_candidates', 'first_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ss_ad_hoc_candidates', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ss_ad_hoc_candidates', 'promoted_by_screener',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('ss_ad_hoc_candidates_ticker_key'), 'ss_ad_hoc_candidates', type_='unique')
    op.create_index(op.f('ix_ss_ad_hoc_candidates_id'), 'ss_ad_hoc_candidates', ['id'], unique=False)
    op.create_unique_constraint('unique_ticker', 'ss_ad_hoc_candidates', ['ticker'])
    op.create_unique_constraint(op.f('uq_ss_ad_hoc_candidates_ticker'), 'ss_ad_hoc_candidates', ['ticker'])
    op.alter_column('ss_alerts', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ss_alerts', 'sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_ss_alerts_alert_level_timestamp'), table_name='ss_alerts')
    op.create_index('idx_ss_alerts_alert_level_timestamp', 'ss_alerts', ['alert_level', 'timestamp'], unique=False, postgresql_using='btree')
    op.drop_index(op.f('idx_ss_alerts_sent_timestamp'), table_name='ss_alerts')
    op.create_index('idx_ss_alerts_sent_timestamp', 'ss_alerts', ['sent', 'timestamp'], unique=False, postgresql_using='btree')
    op.drop_index(op.f('idx_ss_alerts_timestamp_desc'), table_name='ss_alerts')
    op.create_index('idx_ss_alerts_timestamp_desc', 'ss_alerts', ['timestamp'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_ss_alerts_id'), 'ss_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_ss_alerts_ticker'), 'ss_alerts', ['ticker'], unique=False)
    op.alter_column('ss_deep_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_ss_deep_metrics_sentiment24'), table_name='ss_deep_metrics')
    op.drop_constraint(op.f('ss_deep_metrics_ticker_date_key'), 'ss_deep_metrics', type_='unique')
    op.drop_index(op.f('idx_ss_deep_metrics_alert_level'), table_name='ss_deep_metrics')
    op.create_index('idx_ss_deep_metrics_alert_level', 'ss_deep_metrics', ['alert_level', 'date'], unique=False, postgresql_using='btree')
    op.drop_index(op.f('idx_ss_deep_metrics_date_desc'), table_name='ss_deep_metrics')
    op.create_index('idx_ss_deep_metrics_date_desc', 'ss_deep_metrics', ['date'], unique=False, postgresql_using='btree')
    op.drop_index(op.f('idx_ss_deep_metrics_squeeze_score_desc'), table_name='ss_deep_metrics')
    op.create_index('idx_ss_deep_metrics_squeeze_score_desc', 'ss_deep_metrics', ['squeeze_score', 'date'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_ss_deep_metrics_date'), 'ss_deep_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_ss_deep_metrics_id'), 'ss_deep_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_ss_deep_metrics_ticker'), 'ss_deep_metrics', ['ticker'], unique=False)
    op.create_unique_constraint('unique_ticker_date', 'ss_deep_metrics', ['ticker', 'date'])
    op.drop_column('ss_deep_metrics', 'virality_index')
    op.drop_column('ss_deep_metrics', 'sentiment_score_24h')
    op.drop_column('ss_deep_metrics', 'mentions_growth_7d')
    op.drop_column('ss_deep_metrics', 'sentiment_data_quality')
    op.drop_column('ss_deep_metrics', 'bot_pct')
    op.drop_column('ss_deep_metrics', 'mentions_24h')
    op.drop_column('ss_deep_metrics', 'positive_ratio_24h')
    op.drop_column('ss_deep_metrics', 'sentiment_raw_payload')
    op.drop_column('ss_deep_metrics', 'unique_authors_24h')
    op.alter_column('ss_snapshot', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_ss_snapshot_run_date_desc'), table_name='ss_snapshot')
    op.create_index('idx_ss_snapshot_run_date_desc', 'ss_snapshot', ['run_date'], unique=False, postgresql_using='btree')
    op.drop_index(op.f('idx_ss_snapshot_screener_score_desc'), table_name='ss_snapshot')
    op.create_index('idx_ss_snapshot_screener_score_desc', 'ss_snapshot', ['screener_score', 'run_date'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_ss_snapshot_id'), 'ss_snapshot', ['id'], unique=False)
    op.create_index(op.f('ix_ss_snapshot_run_date'), 'ss_snapshot', ['run_date'], unique=False)
    op.create_index(op.f('ix_ss_snapshot_ticker'), 'ss_snapshot', ['ticker'], unique=False)
    op.alter_column('telegram_broadcast_logs', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('telegram_broadcast_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('telegram_command_audits', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('telegram_command_audits', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('telegram_feedbacks', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('telegram_feedbacks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trading_bots', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('trading_bots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trading_bots', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Trading bot description. Defined by the trader, who creates the bot.',
               existing_nullable=True)
    op.create_index(op.f('ix_trading_bots_id'), 'trading_bots', ['id'], unique=False)
    op.alter_column('trading_performance_metrics', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('trading_performance_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_trading_performance_metrics_id'), 'trading_performance_metrics', ['id'], unique=False)
    op.drop_table_comment(
        'trading_performance_metrics',
        existing_comment='Performance metrics for trading strategies',
        schema=None
    )
    op.alter_column('trading_positions', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('trading_positions', 'qty_open',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               server_default=None,
               existing_nullable=False)
    op.alter_column('trading_positions', 'realized_pnl',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_trading_positions_id'), 'trading_positions', ['id'], unique=False)
    op.drop_table_comment(
        'trading_positions',
        existing_comment='Open and closed trading positions',
        schema=None
    )
    op.alter_column('trading_trades', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('trading_trades', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_trading_trades_id'), 'trading_trades', ['id'], unique=False)
    op.drop_table_comment(
        'trading_trades',
        existing_comment='Individual trade records',
        schema=None
    )
    op.alter_column('usr_auth_identities', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.create_index('ix_auth_identities_provider_external', 'usr_auth_identities', ['provider', 'external_id'], unique=False)
    op.create_unique_constraint('uq_auth_identities_provider_external', 'usr_auth_identities', ['provider', 'external_id'])
    op.alter_column('usr_users', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('usr_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('usr_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('usr_users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_unique_constraint(op.f('uq_usr_users_email'), 'usr_users', ['email'])
    op.drop_table_comment(
        'usr_users',
        existing_comment='User accounts and authentication',
        schema=None
    )
    op.alter_column('usr_verification_codes', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('webui_audit_logs', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('webui_performance_snapshots', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('webui_strategy_templates', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('webui_strategy_templates', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('webui_strategy_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('webui_system_config', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('webui_system_config', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('webui_system_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_unique_constraint(op.f('uq_webui_system_config_key'), 'webui_system_config', ['key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_webui_system_config_key'), 'webui_system_config', type_='unique')
    op.alter_column('webui_system_config', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('webui_system_config', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('webui_system_config', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('webui_strategy_templates', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('webui_strategy_templates', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('webui_strategy_templates', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('webui_performance_snapshots', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('webui_audit_logs', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('usr_verification_codes', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'usr_users',
        'User accounts and authentication',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(op.f('uq_usr_users_email'), 'usr_users', type_='unique')
    op.alter_column('usr_users', 'last_login',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('usr_users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('usr_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=True)
    op.alter_column('usr_users', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('uq_auth_identities_provider_external', 'usr_auth_identities', type_='unique')
    op.drop_index('ix_auth_identities_provider_external', table_name='usr_auth_identities')
    op.alter_column('usr_auth_identities', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'trading_trades',
        'Individual trade records',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_trading_trades_id'), table_name='trading_trades')
    op.alter_column('trading_trades', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('trading_trades', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'trading_positions',
        'Open and closed trading positions',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_trading_positions_id'), table_name='trading_positions')
    op.alter_column('trading_positions', 'realized_pnl',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('trading_positions', 'qty_open',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('trading_positions', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'trading_performance_metrics',
        'Performance metrics for trading strategies',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_trading_performance_metrics_id'), table_name='trading_performance_metrics')
    op.alter_column('trading_performance_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('trading_performance_metrics', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_trading_bots_id'), table_name='trading_bots')
    op.alter_column('trading_bots', 'description',
               existing_type=sa.TEXT(),
               comment='Trading bot description. Defined by the trader, who creates the bot.',
               existing_nullable=True)
    op.alter_column('trading_bots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('trading_bots', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('telegram_feedbacks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('telegram_feedbacks', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('telegram_command_audits', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('telegram_command_audits', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('telegram_broadcast_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('telegram_broadcast_logs', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_ss_snapshot_ticker'), table_name='ss_snapshot')
    op.drop_index(op.f('ix_ss_snapshot_run_date'), table_name='ss_snapshot')
    op.drop_index(op.f('ix_ss_snapshot_id'), table_name='ss_snapshot')
    op.drop_index('idx_ss_snapshot_screener_score_desc', table_name='ss_snapshot', postgresql_using='btree')
    op.create_index(op.f('idx_ss_snapshot_screener_score_desc'), 'ss_snapshot', [sa.literal_column('screener_score DESC'), sa.literal_column('run_date DESC')], unique=False)
    op.drop_index('idx_ss_snapshot_run_date_desc', table_name='ss_snapshot', postgresql_using='btree')
    op.create_index(op.f('idx_ss_snapshot_run_date_desc'), 'ss_snapshot', [sa.literal_column('run_date DESC')], unique=False)
    op.alter_column('ss_snapshot', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.add_column('ss_deep_metrics', sa.Column('unique_authors_24h', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ss_deep_metrics', sa.Column('sentiment_raw_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ss_deep_metrics', sa.Column('positive_ratio_24h', sa.REAL(), autoincrement=False, nullable=True))
    op.add_column('ss_deep_metrics', sa.Column('mentions_24h', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ss_deep_metrics', sa.Column('bot_pct', sa.REAL(), autoincrement=False, nullable=True))
    op.add_column('ss_deep_metrics', sa.Column('sentiment_data_quality', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ss_deep_metrics', sa.Column('mentions_growth_7d', sa.REAL(), autoincrement=False, nullable=True))
    op.add_column('ss_deep_metrics', sa.Column('sentiment_score_24h', sa.REAL(), autoincrement=False, nullable=True))
    op.add_column('ss_deep_metrics', sa.Column('virality_index', sa.REAL(), autoincrement=False, nullable=True))
    op.drop_constraint('unique_ticker_date', 'ss_deep_metrics', type_='unique')
    op.drop_index(op.f('ix_ss_deep_metrics_ticker'), table_name='ss_deep_metrics')
    op.drop_index(op.f('ix_ss_deep_metrics_id'), table_name='ss_deep_metrics')
    op.drop_index(op.f('ix_ss_deep_metrics_date'), table_name='ss_deep_metrics')
    op.drop_index('idx_ss_deep_metrics_squeeze_score_desc', table_name='ss_deep_metrics', postgresql_using='btree')
    op.create_index(op.f('idx_ss_deep_metrics_squeeze_score_desc'), 'ss_deep_metrics', [sa.literal_column('squeeze_score DESC'), sa.literal_column('date DESC')], unique=False)
    op.drop_index('idx_ss_deep_metrics_date_desc', table_name='ss_deep_metrics', postgresql_using='btree')
    op.create_index(op.f('idx_ss_deep_metrics_date_desc'), 'ss_deep_metrics', [sa.literal_column('date DESC')], unique=False)
    op.drop_index('idx_ss_deep_metrics_alert_level', table_name='ss_deep_metrics', postgresql_using='btree')
    op.create_index(op.f('idx_ss_deep_metrics_alert_level'), 'ss_deep_metrics', ['alert_level', sa.literal_column('date DESC')], unique=False)
    op.create_unique_constraint(op.f('ss_deep_metrics_ticker_date_key'), 'ss_deep_metrics', ['ticker', 'date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_ss_deep_metrics_sentiment24'), 'ss_deep_metrics', ['sentiment_24h'], unique=False)
    op.alter_column('ss_deep_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_index(op.f('ix_ss_alerts_ticker'), table_name='ss_alerts')
    op.drop_index(op.f('ix_ss_alerts_id'), table_name='ss_alerts')
    op.drop_index('idx_ss_alerts_timestamp_desc', table_name='ss_alerts', postgresql_using='btree')
    op.create_index(op.f('idx_ss_alerts_timestamp_desc'), 'ss_alerts', [sa.literal_column('timestamp DESC')], unique=False)
    op.drop_index('idx_ss_alerts_sent_timestamp', table_name='ss_alerts', postgresql_using='btree')
    op.create_index(op.f('idx_ss_alerts_sent_timestamp'), 'ss_alerts', ['sent', sa.literal_column('timestamp DESC')], unique=False)
    op.drop_index('idx_ss_alerts_alert_level_timestamp', table_name='ss_alerts', postgresql_using='btree')
    op.create_index(op.f('idx_ss_alerts_alert_level_timestamp'), 'ss_alerts', ['alert_level', sa.literal_column('timestamp DESC')], unique=False)
    op.alter_column('ss_alerts', 'sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('ss_alerts', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_ss_ad_hoc_candidates_ticker'), 'ss_ad_hoc_candidates', type_='unique')
    op.drop_constraint('unique_ticker', 'ss_ad_hoc_candidates', type_='unique')
    op.drop_index(op.f('ix_ss_ad_hoc_candidates_id'), table_name='ss_ad_hoc_candidates')
    op.create_unique_constraint(op.f('ss_ad_hoc_candidates_ticker_key'), 'ss_ad_hoc_candidates', ['ticker'], postgresql_nulls_not_distinct=False)
    op.alter_column('ss_ad_hoc_candidates', 'promoted_by_screener',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('ss_ad_hoc_candidates', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('ss_ad_hoc_candidates', 'first_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.create_table_comment(
        'msg_system_health',
        'Health monitoring for notification channels',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_msg_system_health_system'), table_name='msg_system_health')
    op.drop_index(op.f('ix_msg_system_health_status'), table_name='msg_system_health')
    op.drop_index(op.f('ix_msg_system_health_id'), table_name='msg_system_health')
    op.drop_index(op.f('ix_msg_system_health_checked_at'), table_name='msg_system_health')
    op.create_unique_constraint(op.f('msg_channel_health_channel_key'), 'msg_system_health', ['component'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_system_health_unique'), 'msg_system_health', ['system', sa.literal_column("COALESCE(component, ''::character varying)")], unique=True)
    op.create_index(op.f('idx_system_health_system'), 'msg_system_health', ['system'], unique=False)
    op.create_index(op.f('idx_channel_health_status'), 'msg_system_health', ['status'], unique=False)
    op.create_index(op.f('idx_channel_health_checked'), 'msg_system_health', ['checked_at'], unique=False)
    op.alter_column('msg_system_health', 'checked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('msg_system_health', 'failure_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('msg_system_health', 'component',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.create_table_comment(
        'msg_rate_limits',
        'Per-user rate limiting configuration and state',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_msg_rate_limits_user_id'), table_name='msg_rate_limits')
    op.drop_index(op.f('ix_msg_rate_limits_last_refill'), table_name='msg_rate_limits')
    op.drop_index(op.f('ix_msg_rate_limits_id'), table_name='msg_rate_limits')
    op.drop_index(op.f('ix_msg_rate_limits_channel'), table_name='msg_rate_limits')
    op.create_index(op.f('idx_rate_limits_user'), 'msg_rate_limits', ['user_id'], unique=False)
    op.create_index(op.f('idx_rate_limits_last_refill'), 'msg_rate_limits', ['last_refill'], unique=False)
    op.create_index(op.f('idx_rate_limits_channel'), 'msg_rate_limits', ['channel'], unique=False)
    op.alter_column('msg_rate_limits', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('msg_rate_limits', 'last_refill',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_table_comment(
        'msg_messages',
        'Notification messages queue with priority and retry support',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_msg_messages_status'), table_name='msg_messages')
    op.drop_index(op.f('ix_msg_messages_scheduled_for'), table_name='msg_messages')
    op.drop_index(op.f('ix_msg_messages_recipient_id'), table_name='msg_messages')
    op.drop_index(op.f('ix_msg_messages_message_type'), table_name='msg_messages')
    op.drop_index(op.f('ix_msg_messages_locked_by'), table_name='msg_messages')
    op.drop_index(op.f('ix_msg_messages_locked_at'), table_name='msg_messages')
    op.drop_index(op.f('ix_msg_messages_id'), table_name='msg_messages')
    op.drop_index(op.f('ix_msg_messages_created_at'), table_name='msg_messages')
    op.create_index(op.f('idx_msg_messages_type'), 'msg_messages', ['message_type'], unique=False)
    op.create_index(op.f('idx_msg_messages_status'), 'msg_messages', ['status'], unique=False)
    op.create_index(op.f('idx_msg_messages_scheduled'), 'msg_messages', ['scheduled_for'], unique=False)
    op.create_index(op.f('idx_msg_messages_retry_eligible'), 'msg_messages', ['status', 'retry_count', 'max_retries', 'processed_at'], unique=False, postgresql_where="((status)::text = 'FAILED'::text)")
    op.create_index(op.f('idx_msg_messages_recipient'), 'msg_messages', ['recipient_id'], unique=False)
    op.create_index(op.f('idx_msg_messages_priority'), 'msg_messages', ['priority'], unique=False)
    op.create_index(op.f('idx_msg_messages_pending_priority'), 'msg_messages', ['status', 'scheduled_for', 'priority'], unique=False, postgresql_where="((status)::text = 'PENDING'::text)")
    op.create_index(op.f('idx_msg_messages_pending_poll'), 'msg_messages', ['status', 'scheduled_for', 'locked_by', 'locked_at'], unique=False, postgresql_where="((status)::text = 'PENDING'::text)")
    op.create_index(op.f('idx_msg_messages_locked_by'), 'msg_messages', ['locked_by'], unique=False)
    op.create_index(op.f('idx_msg_messages_locked_at'), 'msg_messages', ['locked_at'], unique=False)
    op.create_index(op.f('idx_msg_messages_created'), 'msg_messages', ['created_at'], unique=False)
    op.alter_column('msg_messages', 'max_retries',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=False)
    op.alter_column('msg_messages', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('msg_messages', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'PENDING'::character varying"),
               existing_nullable=False)
    op.alter_column('msg_messages', 'scheduled_for',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('msg_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('msg_messages', 'channels',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False)
    op.alter_column('msg_messages', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'NORMAL'::character varying"),
               existing_nullable=False)
    op.create_table_comment(
        'msg_delivery_status',
        'Per-channel delivery status tracking for each message',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_msg_delivery_status_status'), table_name='msg_delivery_status')
    op.drop_index(op.f('ix_msg_delivery_status_message_id'), table_name='msg_delivery_status')
    op.drop_index(op.f('ix_msg_delivery_status_id'), table_name='msg_delivery_status')
    op.drop_index(op.f('ix_msg_delivery_status_delivered_at'), table_name='msg_delivery_status')
    op.drop_index(op.f('ix_msg_delivery_status_channel'), table_name='msg_delivery_status')
    op.create_index(op.f('idx_delivery_status_status'), 'msg_delivery_status', ['status'], unique=False)
    op.create_index(op.f('idx_delivery_status_message'), 'msg_delivery_status', ['message_id'], unique=False)
    op.create_index(op.f('idx_delivery_status_delivered'), 'msg_delivery_status', ['delivered_at'], unique=False)
    op.create_index(op.f('idx_delivery_status_composite'), 'msg_delivery_status', ['message_id', 'channel', 'status'], unique=False)
    op.create_index(op.f('idx_delivery_status_channel'), 'msg_delivery_status', ['channel'], unique=False)
    op.alter_column('msg_delivery_status', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_table_comment(
        'msg_channel_configs',
        'Channel plugin configuration and settings',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(op.f('uq_msg_channel_configs_channel'), 'msg_channel_configs', type_='unique')
    op.drop_index(op.f('ix_msg_channel_configs_updated_at'), table_name='msg_channel_configs')
    op.drop_index(op.f('ix_msg_channel_configs_id'), table_name='msg_channel_configs')
    op.drop_index(op.f('ix_msg_channel_configs_enabled'), table_name='msg_channel_configs')
    op.create_unique_constraint(op.f('msg_channel_configs_channel_key'), 'msg_channel_configs', ['channel'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_channel_configs_updated'), 'msg_channel_configs', ['updated_at'], unique=False)
    op.create_index(op.f('idx_channel_configs_enabled'), 'msg_channel_configs', ['enabled'], unique=False)
    op.alter_column('msg_channel_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('msg_channel_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('msg_channel_configs', 'timeout_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('30'),
               existing_nullable=False)
    op.alter_column('msg_channel_configs', 'max_retries',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=False)
    op.alter_column('msg_channel_configs', 'rate_limit_per_minute',
               existing_type=sa.INTEGER(),
               server_default=sa.text('60'),
               existing_nullable=False)
    op.alter_column('msg_channel_configs', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_constraint('unique_user_schedule_name', 'job_schedules', type_='unique')
    op.drop_index(op.f('ix_job_schedules_user_id'), table_name='job_schedules')
    op.drop_index(op.f('ix_job_schedules_next_run_at'), table_name='job_schedules')
    op.drop_index(op.f('ix_job_schedules_id'), table_name='job_schedules')
    op.drop_index(op.f('ix_job_schedules_enabled'), table_name='job_schedules')
    op.drop_index('idx_schedules_next_run_at', table_name='job_schedules')
    op.drop_index('idx_schedules_enabled', table_name='job_schedules')
    op.alter_column('job_schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('job_schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('job_schedules', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('job_schedules', 'task_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('job_schedules', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_foreign_key(op.f('job_schedule_runs_job_id_fkey'), 'job_schedule_runs', 'job_schedules', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_job_schedule_runs_id'), table_name='job_schedule_runs')
    op.drop_constraint('ux_runs_job_scheduled_for', 'job_schedule_runs', type_='unique')
    op.create_index(op.f('ux_runs_job_scheduled_for'), 'job_schedule_runs', ['job_type', 'job_id', 'scheduled_for'], unique=True)
    op.alter_column('job_schedule_runs', 'enqueued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('job_schedule_runs', 'job_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('job_schedule_runs', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('sentiment_payloads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sentiment_payloads_pkey'))
    )
    # ### end Alembic commands ###
